application/models.py
from wtforms import StringField

from .extensions import flask_db


class Gene_loc():
    species = StringField()
    gene = StringField()
    chromosome = StringField
    start = StringField
    end = StringField
    direction = StringField(null=False, choices=(('+', '正向'), ('-', '反向'), ('.', '未知方向')))

    class Meta:
        database = flask_db.database


class Gene_seq():
    species = StringField()
    gene = StringField()
    function = StringField()
    seq = StringField()

    class Meta:
        database = flask_db.database


class Gene_struc():
    species = StringField()
    gene = StringField()
    struID = StringField()
    struName = StringField()

    class Meta:
        database = flask_db.database

application/__init__.py
from .app import create_app

application/app.py
from flask import Flask

from .extensions import flask_db
from .configuration import config

app = Flask(__name__)


def create_app(config_name):
    """Creates the app."""
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    configure_extensions(app)
    configure_blueprints(app)

    return app


def configure_extensions(app):
    """Configures the extensions."""

    flask_db.init_app(app)


def configure_blueprints(app):
    from .home import bp_home
    app.register_blueprint(bp_home, url_prefix='/home')

    from .search import bp_search
    app.register_blueprint(bp_search, url_prefix='/search')

    from .statistics import bp_statistics
    app.register_blueprint(bp_statistics, url_prefix='/statistics')

    from .download import bp_download
    app.register_blueprint(bp_download, url_prefix='/download')

    from .publications import bp_publications
    app.register_blueprint(bp_publications, url_prefix='/publications')

application/download/__init__.py
from flask import Blueprint

bp_download = Blueprint('bp_download', __name__)

from . import views

application/download/views.py
from flask import render_template
from . import bp_download


@bp_download.route('/')
@bp_download.route('/download')
def download():
    return render_template('download/download.html')

application/home/__init__.py
from flask import Blueprint

bp_home = Blueprint('bp_home', __name__)

from . import views

application/home/views.py
from flask import render_template
from . import bp_home


@bp_home.route('/base_index1')
def base_index1():
    return render_template('base_index1.html')


@bp_home.route('/home')
def home():
    return render_template('home/home.html')


@bp_home.route('/')
@bp_home.route('/index')
def index():
    return render_template('home/index.html')

application/publications/__init__.py
from flask import Blueprint

bp_publications = Blueprint('bp_publications', __name__)

from . import views

application/publications/views.py
from flask import render_template
from . import bp_publications


@bp_publications.route('/')
@bp_publications.route('/publications')
def publications():
    return render_template('publications/publications.html')

application/search/__init__.py
from flask import Blueprint

bp_search = Blueprint('bp_search', __name__)

from . import views

application/search/views.py
import json

from flask import render_template, request

from application.utilities import *
from . import bp_search


@bp_search.route('/')

@bp_search.route('/search')
def search():
    return render_template('search/search.html')


@bp_search.route('/search1')
def search1():
    species1 = request.args.get("species1")
    gene = request.args.get("gene")
    print(species1)
    where_condition1 = select_locwhere(species=species1, gene=gene)
    seqs1 = select_all(table_name="gene_loc", where_condition=where_condition1)
    jsonstr1 = json.dumps(seqs1, ensure_ascii=False)
    return jsonstr1


@bp_search.route('/search2')
def search2():
    species2 = request.args.get("species2")
    chromosome = request.args.get("chromosome")
    gstart = request.args.get("gstart")
    gend = request.args.get("gend")
    print(species2)
    where_condition2 = select_locwhere(species=species2, chromosome=chromosome, gstart=gstart, gend=gend)
    seqs2 = select_all(table_name="gene_loc", where_condition=where_condition2)
    print(seqs2)
    jsonstr2 = json.dumps(seqs2, ensure_ascii=False)
    return jsonstr2

application/statistics/__init__.py
from flask import Blueprint

bp_statistics = Blueprint('bp_statistics', __name__)

from . import views

application/statistics/views.py
import json

from flask import render_template, request

from application.utilities import *
from . import bp_statistics


@bp_statistics.route('/')
@bp_statistics.route('/statistics')
def statistics():
    return render_template('statistics/statistics.html')


@bp_statistics.route('/statistic')
def statistic():
    fun = request.args.get("fun")
    print(fun)
    where_condition = "function like '%%%s%%'" % (fun)
    seqs = select_all(table_name="gene_seq", where_condition=where_condition)
    print(seqs[1], len(seqs[0]))
    jsonstr = json.dumps(seqs, ensure_ascii=False)
    return jsonstr


@bp_statistics.route('/test')
def test():
    return render_template('statistics/test.html')

# @bp_statistics.route('/list_seq')
# def list_seq():
#     query = Gene_seq.select().order_by(Gene_seq.gene)
#     pg = PaginatedQuery(query, paginate_by=10, page_var='page', check_bounds=True)
#     page = pg.get_page()
#     page_count = pg.get_page_count()
#     seqs = pg.get_object_list()
#     return render_template('statistics/list_seq.html', seqs=seqs, page=page, page_count=page_count)

application/templates/base_index1.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8">
    <title>HoneybeeGDB</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.useso.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/font-awesome/css/font-awesome.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/simple-line-icons/simple-line-icons.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/uniform/css/uniform.default.css') }}" rel="stylesheet"
          type="text/css">
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
    <link href="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/jqvmap.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/morris/morris.css') }}" rel="stylesheet" type="text/css">
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN PAGE STYLES -->
    <link href="{{ url_for('static',filename='admin/pages/css/tasks.css') }}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE STYLES -->
    <!-- BEGIN THEME STYLES -->
    <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
    <link href="{{ url_for('static',filename='global/css/components-rounded.css') }}" id="style_components"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='global/css/plugins.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='admin/layout/css/layout.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='admin/layout/css/themes/default.css') }}" rel="stylesheet"
          type="text/css" id="style_color">
    <link href="{{ url_for('static',filename='admin/layout/css/custom.css') }}" rel="stylesheet" type="text/css">
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="{ url_for('static',filename='admin/img/favicon.ico') }}">
    {#    <link rel="icon" href="http://host/favicon.ico" type="image/x-icon"/>#}
    {#    <link rel="shortcut icon" href="http://host/favicon.ico" type="image/x-icon"/>#}
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body background="{{ url_for('static',filename='admin/img/base_back.gif') }}">

<!-- BEGIN HEADER 标题!!!-->
<div class="page-header">
    <!-- BEGIN HEADER TOP -->
    <div class="page-header-top">
        <div class="container">
            <div class="top-menu">
                <ul class="nav navbar-nav control-label">{# 名称+logo#}
                    <h1><a href="/">
                        <img src="{{ url_for('static',filename='admin/img/logo-default.png') }}"
                             alt="logo" class="logo-default"></a>
                        <a class="navbar-brand" href="{{ url_for('bp_home.home') }}">
                            <font color="#1e90ff"><b>HoneybeeGDB</b></font></a></h1>
                </ul>
            </div>
        </div>
    </div>
    <!-- END HEADER TOP -->
    <!-- BEGIN HEADER MENU -->
    <div class="page-header-menu">
        <div class="container">
            <!-- BEGIN HEADER SEARCH BOX -->
            <form class="search-form" action="" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="query">
                    <span class="input-group-btn">
                        <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                    </span>
                </div>
            </form>
            <!-- END HEADER SEARCH BOX -->
            <!-- BEGIN MEGA MENU --><!--首页、搜索界面🔍、统计、下载、文献-->
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('bp_home.home') }}">HOME</a></li>
                    <li class="active"><a href="{{ url_for('bp_search.search') }}">SEARCH</a></li>
                    <li class="active"><a href="{{ url_for('bp_statistics.statistics') }}">STATISTICS</a></li>
                    <li class="active"><a href="{{ url_for('bp_download.download') }}">DOWNLOAD</a></li>
                    <li class="active"><a href="{{ url_for('bp_publications.publications') }}">PUBLICATIONS</a></li>
                    <li class="active"><a href="{{ url_for('bp_statistics.test') }}">测试🔍</a></li>
                </ul>
            </div>
            <!-- END MEGA MENU -->
        </div>
        <!-- END HEADER MENU -->
    </div>
    <!-- END HEADER MENU -->
</div>
<!-- END HEADER -->

<!-- BEGIN PAGE CONTAINER -->
<div class="page-container">
    <div class="row">
        <!-- BEGIN REGIONAL STATS PORTLET-->
        {% block content %}
            Page content goes here
        {% endblock %}
        <!-- END REGIONAL STATS PORTLET-->
    </div>
</div>
<!-- END PAGE CONTAINER -->

<!-- BEGIN PRE-FOOTER 页脚前!!!-->
<div class="page-prefooter">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>About</h2>
                <p>
                    The main purpose of learning is to query the gene information of honeybee more conveniently and
                    intuitively, so as to further study the gene of honeybee in the future.
                </p>
            </div>
            <div class="col-md-3 col-sm-6 col-xs12 footer-block">
                <h2>Subscribe Email</h2>
                <div class="subscribe-form">
                    <form action="javascript:;">
                        <div class="input-group">
                            <input type="text" placeholder="mail@email.com" class="form-control">
                            <span class="input-group-btn">
							<button class="btn" type="submit">Submit</button>
							</span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>Follow Us On</h2>
                <ul class="social-icons">
                    <li>
                        <a href="javascript:;" data-original-title="rss" class="rss"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="googleplus" class="googleplus"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="youtube" class="youtube"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="vimeo" class="vimeo"></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>Contacts</h2>
                <address class="margin-bottom-40">
                    Phone: 181 8483 8393<br>
                    Email: <a href="mailto:2423947238@qq.com">2423947238@qq.com</a>
                </address>
            </div>
        </div>
    </div>
</div>
<!-- END PRE-FOOTER -->

<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="container">
        <p align="center">2020 &copy; Honeybee gene database by renqiongyan.</p>
    </div>
</div>
<!-- END FOOTER -->

<!--[if lt IE 9]>
<script src="{{ url_for('static',filename='global/plugins/respond.min.js')}}"></script>
<script src="{{ url_for('static',filename='global/plugins/excanvas.min.js')}}"></script>
<![endif]-->
{#<script src="{{ url_for('static',filename='global/plugins/jquery.min.js') }}" type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jquery-migrate.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->#}
{#<script src="{{ url_for('static',filename='global/plugins/jquery-ui/jquery-ui.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/bootstrap/js/bootstrap.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jquery.blockui.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jquery.cokie.min.js') }}" type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/uniform/jquery.uniform.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<!-- END CORE PLUGINS -->#}
{#<!-- BEGIN PAGE LEVEL PLUGINS -->#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/jquery.vmap.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js') }}"#}
{#        type="text/javascript"></script>#}
{#<!-- IMPORTANT! fullcalendar depends on jquery-ui.min.js for drag & drop support -->#}
{#<script src="{{ url_for('static',filename='global/plugins/morris/morris.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/morris/raphael-min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='global/plugins/jquery.sparkline.min.js') }}"#}
{#        type="text/javascript"></script>#}
{#<!-- END PAGE LEVEL PLUGINS -->#}
{#<!-- BEGIN PAGE LEVEL SCRIPTS -->#}
{#<script src="{{ url_for('static',filename='global/scripts/metronic.js') }}" type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='admin/layout/scripts/layout.js') }}" type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='admin/layout/scripts/demo.js') }}" type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='admin/pages/scripts/index3.js') }}" type="text/javascript"></script>#}
{#<script src="{{ url_for('static',filename='admin/pages/scripts/tasks.js') }}" type="text/javascript"></script>#}
{#<!-- END PAGE LEVEL SCRIPTS -->#}
{#<script>#}
{#    jQuery(document).ready(function () {#}
{#        Metronic.init(); // init metronic core componets#}
{#        Layout.init(); // init layout#}
{#        Demo.init(); // init demo(theme settings page)#}
{#        Index.init(); // init index page#}
{#        Tasks.initDashboardWidget(); // init tash dashboard widget#}
{#    });#}
{#</script>#}
{#<!-- END JAVASCRIPTS -->#}
</div>
</body>
<!-- END BODY -->
</html>

application/templates/flash.html
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
    <div style="color: red">
    <h4>错误：</h4>
    <p>{{ message }}</p>
    </div>
  {% elif category == 'warning' %}
    <div style="color:yellow;">
    <h4>警告：</h4>
    <p>{{ message }}</p>
    </div>
  {% elif category == 'success' %}
    <div style="color: green">
    <h4>成功：</h4>
    <p>{{ message }}</p>
    </div>
  {% else %}
    <div style="color: blue">
    <h4>通知：</h4>
    <p>{{ message }}</p>
    </div>
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}

application/templates/home/home.html
{% extends 'base_index1.html' %}
<!-- BEGIN  centent -->
{% block content %}
    <div class="container about">
        <h2><img src="{{ url_for('static',filename='admin/img/gene-home.png') }}"
                 alt="logo" class="logo-default">About HoneyBee Gene Database</h2>
        <hr>
        <p align="center"><img src="{{ url_for('static',filename='admin/img/gene.png') }}"
                               style="width: auto"></p>
        <p>Bee is a haploid diploid organism, its female is a diploid male is a haploid and the male does not have
            meiosis in the process of sperm production, so its haploid diploid has obvious sex determining mechanism.
        </p>
        <p>Studying bees can help us understand many health problems, such as immune response, allergic reaction,
            metabolic disease, X chromosome disease, etc. The study of genetic structure diversity and gene location
            by using molecular biology technology can effectively study the population genetic structure of bee
            parasitic mite, the evolution of the genome, brain function, sexual function, immune response and disease
            defense mechanism, pattern differentiation, etc.
        </p>
    </div>
{% endblock %}
<!-- END  centent -->

application/templates/home/index.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8">
    <title>HoneybeeGDB</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.useso.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/font-awesome/css/font-awesome.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/simple-line-icons/simple-line-icons.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/uniform/css/uniform.default.css') }}" rel="stylesheet"
          type="text/css">
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
    <link href="{{ url_for('static',filename='global/plugins/jqvmap/jqvmap/jqvmap.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename='global/plugins/morris/morris.css') }}" rel="stylesheet" type="text/css">
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN PAGE STYLES -->
    <link href="{{ url_for('static',filename='admin/pages/css/tasks.css') }}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE STYLES -->
    <!-- BEGIN THEME STYLES -->
    <!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
    <link href="{{ url_for('static',filename='global/css/components-rounded.css') }}" id="style_components"
          rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='global/css/plugins.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='admin/layout/css/layout.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename='admin/layout/css/themes/default.css') }}" rel="stylesheet"
          type="text/css" id="style_color">
    <link href="{{ url_for('static',filename='admin/layout/css/custom.css') }}" rel="stylesheet" type="text/css">
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico">
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->

<body background="{{ url_for('static',filename='admin/img/black.gif') }}">
<!-- BEGIN HEADER 标题!!!-->
<div class="page-header">
    <!-- BEGIN HEADER TOP -->
    <div class="page-header-top">
        <div class="container">
            <div class="top-menu">
                <ul class="nav navbar-nav control-label">{# 名称+logo#}
                    <h1><a href="/">
                        <img src="{{ url_for('static',filename='admin/img/logo-default.png') }}"
                             alt="logo" class="logo-default"></a>
                        <a class="navbar-brand" href="{{ url_for('bp_home.home') }}">
                            <font color="#1e90ff"><b>HoneybeeGDB</b></font></a></h1>
                </ul>
            </div>
        </div>
    </div>
    <!-- END HEADER TOP -->
    <!-- BEGIN HEADER MENU -->
    <div class="page-header-menu">
        <div class="container">
            <!-- BEGIN HEADER SEARCH BOX -->
            <form class="search-form" action="search" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="query">
                    <span class="input-group-btn">
                        <a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
                    </span>
                </div>
            </form>
            <!-- END HEADER SEARCH BOX -->
            <!-- BEGIN MEGA MENU --><!--首页、搜索界面🔍、统计、下载、文献-->
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('bp_home.home') }}">HOME</a></li>
                    <li class="active"><a href="{{ url_for('bp_search.search') }}">SEARCH</a></li>
                    <li class="active"><a href="{{ url_for('bp_statistics.statistics') }}">STATISTICS</a></li>
                    <li class="active"><a href="{{ url_for('bp_download.download') }}">DOWNLOAD</a></li>
                    <li class="active"><a href="{{ url_for('bp_publications.publications') }}">PUBLICATIONS</a></li>
                    <li class="active"><a href="{{ url_for('bp_statistics.test') }}">测试🔍</a></li>
                </ul>
            </div>
            <!-- END MEGA MENU -->
        </div>
        <!-- END HEADER MENU -->
    </div>
    <!-- END HEADER MENU -->
</div>
<!-- END HEADER -->

<!-- BEGIN PAGE CONTAINER index欢迎界面单独设计-->
<div class="container about">
    <h2><img src="{{ url_for('static',filename='admin/img/hi_grey.png') }}"
             alt="logo" class="logo-default"><font color="#f0f8ff">Welcome</font></h2>
    <br><br><br><br><br><br><br>
    <p class="web-font" align="center">
        <font color="#f0f8ff" size="35">
            <b> Welcome to<br>
                HoneyBee Gene Database!</b>
        </font>
    </p>
    <br><br><br>
    <p align="center">
        <img src="{{ url_for('static',filename='admin/img/welcome_circle_grey.png') }}">
    </p>
    <br><br><br>
</div>
<!-- END PAGE CONTAINER -->

<!-- BEGIN PRE-FOOTER 页脚前!!!-->
<div class="page-prefooter">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>About</h2>
                <p>
                    The main purpose of learning is to query the gene information of honeybee more conveniently and
                    intuitively, so as to further study the gene of honeybee in the future.
                </p>
            </div>
            <div class="col-md-3 col-sm-6 col-xs12 footer-block">
                <h2>Subscribe Email</h2>
                <div class="subscribe-form">
                    <form action="javascript:;">
                        <div class="input-group">
                            <input type="text" placeholder="mail@email.com" class="form-control">
                            <span class="input-group-btn">
							<button class="btn" type="submit">Submit</button>
							</span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>Follow Us On</h2>
                <ul class="social-icons">
                    <li>
                        <a href="javascript:;" data-original-title="rss" class="rss"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="facebook" class="facebook"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="twitter" class="twitter"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="googleplus" class="googleplus"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="linkedin" class="linkedin"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="youtube" class="youtube"></a>
                    </li>
                    <li>
                        <a href="javascript:;" data-original-title="vimeo" class="vimeo"></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12 footer-block">
                <h2>Contacts</h2>
                <address class="margin-bottom-40">
                    Phone: 181 8483 8393<br>
                    Email: <a href="mailto:2423947238@qq.com">2423947238@qq.com</a>
                </address>
            </div>
        </div>
    </div>
</div>
<!-- END PRE-FOOTER -->

<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="container">
        <p align="center">2020 &copy; Honeybee gene database by renqiongyan.</p>
    </div>
</div>
<!-- END FOOTER -->

<!--[if lt IE 9]>
<script src="{{ url_for('static',filename='global/plugins/respond.min.js')}}"></script>
<script src="{{ url_for('static',filename='global/plugins/excanvas.min.js')}}"></script>
<![endif]-->
</div>
</body>
<!-- END BODY -->
</html>